import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;

class Retrieving_AutoGenerated_values {
   
    public static void main(String args[]) throws SQLException {
      
    	DriverManager.registerDriver(new com.mysql.jdbc.Driver());
      
    	String mysqlUrl = "jdbc:mysql://localhost/sample_database";
    	Connection con = DriverManager.getConnection(mysqlUrl, "root", "password");
    	System.out.println("Connection established......");
      
    	String insertQuery = "INSERT INTO Sales (ProductName, CustomerName, DispatchDate, DeliveryTime, Price, Location) VALUES (?, ?, ?, ?, ?, ?)";
      
     	PreparedStatement pstmt = con.prepareStatement(insertQuery,Statement.RETURN_GENERATED_KEYS);
    	pstmt.setString(1, "Key-Board");
    	pstmt.setString(2, "Raja");
    	pstmt.setDate(3, new Date(1567315800000L));
    	pstmt.setTime(4, new Time(1567315800000L));
    	pstmt.setInt(5, 7000);
    	pstmt.setString(6, "Hyderabad");
    	pstmt.addBatch();
      
      	pstmt.executeBatch();
      
     	ResultSet res = pstmt.getGeneratedKeys();
      	System.out.println("Auto-incremented values of the column ID generated by the current PreparedStatement object: ");
      	while (res.next()) {
        	
        	System.out.println(res.getString(1));
      }
   }
}